# Auto-generated name banks for procedural person generation
# DO NOT EDIT — regenerate with: python build_name_banks.py

NAME_BANKS = [
    {
        "nationality": "American",
        "region": "north_america",
        "weight": 5.0,
        "first_m": ["James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Andrew", "Paul", "Joshua", "Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald", "Edward", "Jason", "Jeffrey", "Ryan", "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon", "Benjamin", "Samuel", "Raymond", "Gregory", "Frank", "Alexander", "Patrick", "Jack", "Dennis", "Jerry", "Tyler", "Aaron", "Jose", "Nathan", "Henry", "Douglas", "Peter", "Zachary", "Kyle", "Noah", "Ethan", "Jeremy", "Walter", "Christian", "Keith", "Roger", "Terry", "Austin", "Sean", "Gerald", "Carl", "Harold", "Dylan", "Arthur", "Lawrence", "Jordan", "Jesse", "Bryan", "Billy", "Bruce", "Albert", "Willie", "Gabriel", "Logan", "Ralph", "Roy", "Eugene", "Russell", "Randy", "Philip", "Vincent", "Bobby", "Johnny", "Bradley", "Elijah", "Mason", "Liam", "Aiden", "Luke", "Owen"],
        "first_f": ["Mary", "Patricia", "Jennifer", "Linda", "Barbara", "Elizabeth", "Susan", "Jessica", "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Margaret", "Sandra", "Ashley", "Dorothy", "Kimberly", "Emily", "Donna", "Michelle", "Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Sharon", "Laura", "Cynthia", "Kathleen", "Amy", "Angela", "Shirley", "Anna", "Brenda", "Pamela", "Emma", "Nicole", "Helen", "Samantha", "Katherine", "Christine", "Debra", "Rachel", "Carolyn", "Janet", "Catherine", "Maria", "Heather", "Diane", "Ruth", "Julie", "Olivia", "Joyce", "Virginia", "Victoria", "Kelly", "Lauren", "Christina", "Joan", "Evelyn", "Judith", "Megan", "Andrea", "Cheryl", "Hannah", "Jacqueline", "Martha", "Gloria", "Teresa", "Ann", "Sara", "Madison", "Frances", "Kathryn", "Janice", "Jean", "Abigail", "Alice", "Judy", "Sophia", "Grace", "Denise", "Amber", "Doris", "Marilyn", "Danielle", "Beverly", "Isabella", "Theresa", "Diana", "Natalie", "Brittany", "Charlotte", "Marie", "Kayla", "Alexis", "Lori", "Ava"],
        "surnames": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster", "Jimenez"],
    },
    {
        "nationality": "African-American",
        "region": "north_america",
        "weight": 2.0,
        "first_m": ["DeAndre", "Jamal", "Malik", "Tyrone", "Darnell", "Terrence", "Lamar", "Cedric", "Dwayne", "Marcus", "Andre", "Jalen", "Kareem", "Rashid", "Desmond", "Marquis", "Kendrick", "Darius", "Donovan", "Dante", "Hakeem", "Isaiah", "Khalil", "Omari", "Trevon", "Xavier", "Jabari", "Kofi", "Langston", "Nehemiah", "Sterling", "Tobias", "Wendell", "Bryson", "Colston", "Devante", "Elijah", "Floyd", "Glenn", "Harlan"],
        "first_f": ["Aaliyah", "Imani", "Keisha", "Latoya", "Tamika", "Shaniqua", "Ebony", "Jasmine", "Destiny", "Diamond", "Monique", "Tanisha", "Aliyah", "Brianna", "Ciara", "Dominique", "Nia", "Precious", "Raven", "Sade", "Tiffany", "Zora", "Amara", "Beyonce", "Chandra", "Desiree", "Fatima", "Gaelle", "Hadiya", "Janelle", "Kendra", "Lakeisha", "Malika", "Naomi", "Octavia", "Portia", "Rhiannon", "Simone", "Tiana", "Vivica"],
        "surnames": ["Washington", "Jefferson", "Freeman", "Banks", "Booker", "Chambers", "Coleman", "Crawford", "Daniels", "Ellis", "Franklin", "Gibson", "Hampton", "Ingram", "Jacobs", "Knox", "Lambert", "Mason", "Nash", "Owens", "Palmer", "Quinn", "Randolph", "Simmons", "Tucker", "Underwood", "Vaughn", "Wallace", "Yates", "Barton", "Cleveland", "Douglas", "Emerson", "Floyd", "Garrison", "Haynes", "Irvin", "Jennings", "Kincaid", "Lawson"],
    },
    {
        "nationality": "Canadian",
        "region": "north_america",
        "weight": 1.5,
        "first_m": ["Liam", "Noah", "Oliver", "Ethan", "Lucas", "Mason", "Logan", "Alexander", "Jack", "Benjamin", "Theo", "Hudson", "Finn", "Callum", "Declan", "Owen", "Felix", "Jasper", "Connor", "Rory", "Tristan", "Graham", "Malcolm", "Duncan", "Gavin", "Reid", "Murray", "Fraser", "Nolan", "Bryce"],
        "first_f": ["Emma", "Olivia", "Charlotte", "Amelia", "Sophia", "Isla", "Ava", "Mia", "Ivy", "Freya", "Chloe", "Zoe", "Nora", "Hazel", "Stella", "Maeve", "Clara", "Fiona", "Eloise", "Genevieve", "Margot", "Celeste", "Ingrid", "Astrid", "Iris", "Dahlia", "Rosalie", "Laurel", "Simone", "Adele"],
        "surnames": ["Tremblay", "Gagnon", "Roy", "Côté", "Bouchard", "Gauthier", "Morin", "Lavoie", "Fortin", "Gagné", "Ouellet", "Pelletier", "Bélanger", "Lévesque", "Bergeron", "Leblanc", "Paquette", "Girard", "Simard", "Boucher", "Campbell", "MacDonald", "MacLeod", "Morrison", "Robertson", "Henderson", "Stewart", "Murray", "Fraser", "Johnston"],
    },
    {
        "nationality": "British",
        "region": "europe",
        "weight": 4.0,
        "first_m": ["Oliver", "Harry", "George", "Jack", "Charlie", "Thomas", "Oscar", "William", "James", "Henry", "Alfie", "Edward", "Arthur", "Leo", "Noah", "Freddie", "Archie", "Theo", "Alexander", "Max", "Sebastian", "Rupert", "Hugo", "Felix", "Edmund", "Benedict", "Jasper", "Tobias", "Alistair", "Cedric", "Nigel", "Colin", "Trevor", "Geoffrey", "Reginald", "Neville", "Basil", "Clive", "Derek", "Malcolm"],
        "first_f": ["Olivia", "Amelia", "Isla", "Ava", "Emily", "Sophia", "Grace", "Mia", "Poppy", "Ella", "Lily", "Rosie", "Florence", "Freya", "Willow", "Ivy", "Phoebe", "Evie", "Scarlett", "Charlotte", "Imogen", "Harriet", "Jemima", "Pippa", "Gemma", "Bronwen", "Fiona", "Rowena", "Beatrice", "Helena", "Millicent", "Penelope", "Cecily", "Daphne", "Elspeth", "Fenella", "Gwendolen", "Hermione", "Lavinia", "Margot"],
        "surnames": ["Smith", "Jones", "Williams", "Taylor", "Brown", "Davies", "Evans", "Wilson", "Thomas", "Roberts", "Johnson", "Walker", "Wright", "Thompson", "Robinson", "White", "Hall", "Green", "Harris", "Clarke", "Patel", "Jackson", "Wood", "Turner", "Martin", "Cooper", "Hill", "Ward", "Morris", "Moore", "King", "Watson", "Harrison", "Morgan", "Hughes", "Edwards", "Baker", "Collins", "Price", "Bennett", "Ashworth", "Blackwood", "Carmichael", "Davenport", "Fairfax", "Grimshaw", "Harrington", "Kingsley", "Pemberton", "Whitfield"],
    },
    {
        "nationality": "French",
        "region": "europe",
        "weight": 3.0,
        "first_m": ["Jean", "Pierre", "Michel", "Jacques", "François", "Philippe", "André", "Louis", "Henri", "René", "Claude", "Alain", "Bernard", "Yves", "Gérard", "Thierry", "Didier", "Pascal", "Stéphane", "Christophe", "Mathieu", "Antoine", "Nicolas", "Raphaël", "Maxime", "Julien", "Cédric", "Fabien", "Gaël", "Loïc", "Bastien", "Étienne", "Rémy", "Sébastien", "Aurélien", "Damien", "Florian", "Grégoire", "Hervé", "Lucien"],
        "first_f": ["Marie", "Jeanne", "Françoise", "Monique", "Catherine", "Nathalie", "Isabelle", "Sylvie", "Valérie", "Sophie", "Camille", "Chloé", "Léa", "Manon", "Inès", "Émilie", "Anaïs", "Margaux", "Céline", "Aurélie", "Élodie", "Mélanie", "Charlotte", "Adèle", "Colette", "Delphine", "Geneviève", "Hélène", "Joséphine", "Madeleine", "Noémie", "Océane", "Pauline", "Romane", "Solène", "Thérèse", "Vivienne", "Yvette", "Zoé", "Apolline"],
        "surnames": ["Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau", "Simon", "Laurent", "Lefebvre", "Michel", "Garcia", "David", "Bertrand", "Roux", "Vincent", "Fournier", "Morel", "Girard", "André", "Lefèvre", "Mercier", "Dupont", "Lambert", "Bonnet", "François", "Martinez", "Beaumont", "Chevalier", "Delacroix", "Fontaine", "Gauthier", "Joubert", "Lemaire", "Marchand", "Perrin", "Rousseau"],
    },
    {
        "nationality": "German",
        "region": "europe",
        "weight": 3.0,
        "first_m": ["Hans", "Klaus", "Wolfgang", "Jürgen", "Dieter", "Helmut", "Rainer", "Manfred", "Stefan", "Markus", "Thomas", "Michael", "Andreas", "Christian", "Matthias", "Sebastian", "Florian", "Tobias", "Maximilian", "Felix", "Lukas", "Jonas", "Leon", "Finn", "Moritz", "Niklas", "Philipp", "Bastian", "Bernhard", "Christoph", "Dominik", "Friedrich", "Gustav", "Heinrich", "Joachim", "Karl", "Leopold", "Otto", "Rüdiger", "Werner"],
        "first_f": ["Anna", "Maria", "Ursula", "Helga", "Monika", "Petra", "Sabine", "Andrea", "Stefanie", "Claudia", "Katharina", "Elisabeth", "Brigitte", "Renate", "Ingrid", "Heike", "Birgit", "Gabriele", "Susanne", "Ulrike", "Hannah", "Lena", "Emma", "Mia", "Sophie", "Johanna", "Frieda", "Anneliese", "Gretchen", "Hildegard", "Marlene", "Liesel", "Elke", "Dagmar", "Ilse", "Gertrud", "Hannelore", "Waltraud", "Roswitha", "Elfriede"],
        "surnames": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Krause", "Meier", "Lehmann", "Brandt", "Bergmann", "Engel", "Fiedler", "Günther", "Hahn", "Kaiser", "Lorenz", "Pfeiffer", "Vogt"],
    },
    {
        "nationality": "Italian",
        "region": "europe",
        "weight": 2.5,
        "first_m": ["Marco", "Giuseppe", "Giovanni", "Antonio", "Francesco", "Alessandro", "Andrea", "Luca", "Matteo", "Lorenzo", "Leonardo", "Davide", "Federico", "Simone", "Riccardo", "Nicola", "Stefano", "Roberto", "Fabio", "Daniele", "Vincenzo", "Salvatore", "Massimo", "Giacomo", "Emanuele", "Claudio", "Gianluca", "Paolo", "Carlo", "Enrico", "Alfredo", "Bruno", "Cesare", "Domenico", "Enzo", "Filippo", "Gianfranco", "Ignazio", "Luigi", "Marcello"],
        "first_f": ["Maria", "Anna", "Giulia", "Francesca", "Sara", "Laura", "Chiara", "Valentina", "Alessandra", "Elisa", "Federica", "Silvia", "Martina", "Paola", "Roberta", "Simona", "Elena", "Monica", "Daniela", "Barbara", "Beatrice", "Camilla", "Ilaria", "Elisabetta", "Sofia", "Aurora", "Ginevra", "Ludovica", "Vittoria", "Arianna", "Carlotta", "Fiamma", "Grazia", "Isabella", "Luciana", "Margherita", "Nicoletta", "Ornella", "Patrizia", "Raffaella"],
        "surnames": ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco", "Bruno", "Gallo", "Conti", "De Luca", "Mancini", "Costa", "Giordano", "Rizzo", "Lombardi", "Moretti", "Barbieri", "Fontana", "Santoro", "Mariani", "Rinaldi", "Caruso", "Ferrara", "Galli", "Martini", "Leone", "Amato", "Bellini", "Cattaneo", "Damico", "Fabbri", "Gentile", "Innocenti", "Longo", "Monti", "Parisi"],
    },
    {
        "nationality": "Spanish",
        "region": "europe",
        "weight": 2.5,
        "first_m": ["Carlos", "Miguel", "Antonio", "José", "Francisco", "Manuel", "David", "Javier", "Alejandro", "Daniel", "Fernando", "Rafael", "Pablo", "Sergio", "Andrés", "Jorge", "Álvaro", "Diego", "Raúl", "Adrián", "Ignacio", "Gonzalo", "Enrique", "Eduardo", "Rodrigo", "Guillermo", "Óscar", "Iñigo", "Víctor", "Marcos", "Alfonso", "Benito", "Cristóbal", "Esteban", "Felipe", "Hector", "Ismael", "Jesús", "Lorenzo", "Nicolás"],
        "first_f": ["María", "Carmen", "Ana", "Isabel", "Laura", "Lucía", "Marta", "Elena", "Cristina", "Sara", "Paula", "Rocío", "Silvia", "Beatriz", "Andrea", "Alba", "Irene", "Nuria", "Patricia", "Alicia", "Pilar", "Consuelo", "Dolores", "Esperanza", "Guadalupe", "Inmaculada", "Josefa", "Lourdes", "Mercedes", "Rosario", "Amparo", "Blanca", "Catalina", "Elvira", "Fernanda", "Graciela", "Helena", "Jimena", "Leticia", "Macarena"],
        "surnames": ["García", "Martínez", "López", "Sánchez", "González", "Rodríguez", "Fernández", "Pérez", "Gómez", "Díaz", "Hernández", "Álvarez", "Moreno", "Muñoz", "Jiménez", "Ruiz", "Romero", "Navarro", "Torres", "Domínguez", "Vázquez", "Ramos", "Gil", "Serrano", "Blanco", "Molina", "Suárez", "Castro", "Ortega", "Delgado", "Aguilar", "Caballero", "Cárdenas", "Espinoza", "Fuentes", "Gallego", "Ibáñez", "Lara", "Medina", "Prieto"],
    },
    {
        "nationality": "Japanese",
        "region": "east_asia",
        "weight": 3.0,
        "first_m": ["Takeshi", "Hiroshi", "Kenji", "Yusuke", "Ryota", "Haruki", "Daiki", "Shota", "Kazuki", "Ryo", "Naoki", "Satoshi", "Takumi", "Kenta", "Yuto", "Akira", "Taro", "Shin", "Makoto", "Ren", "Sosuke", "Hayato", "Kaito", "Minato", "Isamu", "Jiro", "Koji", "Masato", "Noboru", "Osamu"],
        "first_f": ["Yuko", "Akiko", "Keiko", "Sachiko", "Haruka", "Aoi", "Yui", "Hana", "Sakura", "Rin", "Ayumi", "Megumi", "Nanami", "Miki", "Emi", "Noriko", "Tomoko", "Chihiro", "Misaki", "Kaori", "Asuka", "Fumiko", "Izumi", "Kiyoko", "Mariko", "Natsuki", "Reiko", "Sayuri", "Tamiko", "Yoshiko"],
        "surnames": ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato", "Yoshida", "Yamada", "Sasaki", "Yamaguchi", "Matsumoto", "Inoue", "Kimura", "Shimizu", "Hayashi", "Saito", "Abe", "Mori", "Ikeda", "Hashimoto", "Fujita", "Ogawa", "Okada", "Murata", "Nishida", "Endo"],
    },
    {
        "nationality": "South Korean",
        "region": "east_asia",
        "weight": 2.5,
        "first_m": ["Min-jun", "Seo-jun", "Do-yun", "Ji-ho", "Ha-jun", "Ye-jun", "Jun-seo", "Hyun-woo", "Tae-min", "Jae-hyun", "Sung-ho", "Woo-jin", "Dong-hyun", "Seung-gi", "Byung-hun", "Si-woo", "Yong-ha", "Chan-woo", "Jin-woo", "Ki-tae", "Dae-jung", "Eun-ho", "Gi-hun", "In-sung", "Joon-ki", "Kyung-ho", "Myung-soo", "Nam-joon", "Sang-woo", "Won-bin"],
        "first_f": ["Ji-yeon", "Soo-jin", "Min-ji", "Ye-jin", "Seo-yeon", "Ha-yeon", "Da-hye", "Eun-bi", "Yuna", "Hye-jin", "Su-yeon", "Bo-young", "Shin-hye", "Ji-won", "Hae-in", "Na-young", "So-yeon", "Yoo-jin", "Ah-reum", "Chae-won", "Da-som", "Ga-young", "Hyo-rin", "In-young", "Joo-hyun", "Mi-ran", "Na-ri", "Se-ri", "Ye-rin", "Sun-hee"],
        "surnames": ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim", "Han", "Oh", "Seo", "Shin", "Kwon", "Hwang", "Ahn", "Song", "Yoo", "Hong", "Bae", "Baek", "Cha", "Go", "Ha", "Heo", "Hyun", "Ko", "Moon", "Nam"],
    },
    {
        "nationality": "Chinese",
        "region": "east_asia",
        "weight": 3.5,
        "first_m": ["Wei", "Fang", "Lei", "Jun", "Ming", "Hao", "Cheng", "Jian", "Tao", "Xiang", "Biao", "Dong", "Gang", "Hui", "Kai", "Liang", "Peng", "Qiang", "Rui", "Sheng", "Ting", "Wen", "Xin", "Yi", "Zhi", "Bo", "Chen", "Da", "Feng", "Guo", "Han", "Jie", "Long", "Nan", "Ping", "Shan", "Tian", "Xiao", "Yu", "Zhen"],
        "first_f": ["Xia", "Ling", "Mei", "Yan", "Jing", "Fei", "Yue", "Lan", "Hua", "Rong", "Ai", "Bi", "Cui", "Dan", "En", "Fang", "Gui", "Hong", "Jia", "Li", "Min", "Ni", "Qi", "Ru", "Si", "Ting", "Wei", "Xi", "Yin", "Zhu", "Bao", "Chun", "Die", "Fen", "Huan", "Juan", "Lian", "Nuo", "Qin", "Shu"],
        "surnames": ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou", "Xu", "Sun", "Ma", "Zhu", "Hu", "Guo", "Lin", "He", "Gao", "Luo", "Zheng", "Liang", "Xie", "Tang", "Han", "Cao", "Deng", "Feng", "Jiang", "Shen", "Xiao", "Ye", "Cheng", "Gu", "Hou", "Kong", "Lu", "Pan", "Qian", "Wan"],
    },
    {
        "nationality": "Indian",
        "region": "south_asia",
        "weight": 4.0,
        "first_m": ["Aarav", "Arjun", "Vikram", "Raj", "Ravi", "Arun", "Sanjay", "Amit", "Rohit", "Varun", "Kiran", "Nikhil", "Pranav", "Suresh", "Ajay", "Deepak", "Ganesh", "Hari", "Ishaan", "Jai", "Krishna", "Lakshman", "Mohan", "Naveen", "Om", "Pavan", "Rakesh", "Sachin", "Tarun", "Uday", "Venkat", "Yash", "Aditya", "Bharat", "Chandan", "Dev", "Gaurav", "Hemant", "Kabir", "Manish"],
        "first_f": ["Priya", "Ananya", "Aisha", "Meera", "Neha", "Pooja", "Rani", "Sunita", "Divya", "Kavya", "Shreya", "Tanvi", "Uma", "Vidya", "Aditi", "Bhavna", "Chitra", "Durga", "Esha", "Fatima", "Geeta", "Hema", "Isha", "Jyoti", "Kamala", "Lakshmi", "Maya", "Nandini", "Padma", "Radha", "Sarita", "Tara", "Usha", "Vani", "Anita", "Deepa", "Indira", "Kalpana", "Madhuri", "Nisha"],
        "surnames": ["Sharma", "Patel", "Singh", "Kumar", "Shah", "Gupta", "Mehta", "Joshi", "Reddy", "Nair", "Rao", "Desai", "Pillai", "Iyer", "Menon", "Verma", "Mishra", "Agarwal", "Bhatt", "Chatterjee", "Deshpande", "Ghosh", "Hegde", "Kapoor", "Kulkarni", "Mukherjee", "Patil", "Rajan", "Varma", "Banerjee", "Bose", "Chowdhury", "Das", "Ganesh", "Kakkar", "Malhotra", "Pandey", "Saxena", "Thakur", "Trivedi"],
    },
    {
        "nationality": "Mexican",
        "region": "latin_america",
        "weight": 2.5,
        "first_m": ["Diego", "Santiago", "Mateo", "Emiliano", "Sebastián", "Alejandro", "Rafael", "Andrés", "Fernando", "Ricardo", "Hugo", "Arturo", "Enrique", "César", "Raúl", "Ernesto", "Gustavo", "Cuauhtémoc", "Braulio", "Octavio", "Abelardo", "Baltazar", "Cipriano", "Demetrio", "Eleuterio", "Fidencio", "Gervasio", "Hermenegildo", "Inocencio", "Juventino"],
        "first_f": ["Valentina", "Sofía", "Regina", "Camila", "Ximena", "Fernanda", "Isabella", "Renata", "Daniela", "Mariana", "Guadalupe", "Itzel", "Citlali", "Xóchitl", "Paloma", "Marisol", "Rocío", "Dulce", "Esperanza", "Montserrat", "Araceli", "Berenice", "Conchita", "Dolores", "Elvia", "Flor", "Graciela", "Hortensia", "Itzayana", "Josefina"],
        "surnames": ["González", "Hernández", "López", "Martínez", "García", "Rodríguez", "Pérez", "Sánchez", "Ramírez", "Cruz", "Flores", "Gómez", "Morales", "Vásquez", "Jiménez", "Torres", "Reyes", "Díaz", "Guzmán", "Medina", "Aguilar", "Castillo", "Chávez", "Delgado", "Espinoza", "Fuentes", "Guerrero", "Herrera", "Ibarra", "Juárez"],
    },
    {
        "nationality": "Brazilian",
        "region": "latin_america",
        "weight": 2.0,
        "first_m": ["João", "Pedro", "Lucas", "Matheus", "Gabriel", "Rafael", "Gustavo", "Thiago", "Bruno", "Fernando", "Caio", "Henrique", "Vinícius", "Bernardo", "Eduardo", "Felipe", "Leandro", "Marcelo", "Otávio", "Renato", "Adriano", "Benedito", "Clóvis", "Donizete", "Edvaldo", "Flávio", "Gilberto", "Heraldo", "Irineu", "Josué"],
        "first_f": ["Ana", "Maria", "Fernanda", "Juliana", "Camila", "Beatriz", "Larissa", "Amanda", "Carolina", "Gabriela", "Letícia", "Mariana", "Natália", "Patrícia", "Rafaela", "Sabrina", "Tatiana", "Valéria", "Bianca", "Clarice", "Daiane", "Eliane", "Fátima", "Gisele", "Heloísa", "Iara", "Janaína", "Keila", "Lorena", "Miriam"],
        "surnames": ["Silva", "Santos", "Oliveira", "Souza", "Lima", "Pereira", "Ferreira", "Costa", "Rodrigues", "Almeida", "Nascimento", "Araújo", "Melo", "Barbosa", "Ribeiro", "Carvalho", "Cardoso", "Correia", "Gomes", "Martins", "Andrade", "Batista", "Cavalcanti", "Duarte", "Evangelista", "Farias", "Gonçalves", "Lopes", "Machado", "Nogueira"],
    },
    {
        "nationality": "Argentine",
        "region": "latin_america",
        "weight": 1.5,
        "first_m": ["Matías", "Nicolás", "Facundo", "Agustín", "Tomás", "Joaquín", "Lautaro", "Maximiliano", "Franco", "Gonzalo", "Hernán", "Ignacio", "Leandro", "Martín", "Pablo", "Ramiro", "Santiago", "Valentín", "Bautista", "Ezequiel"],
        "first_f": ["Valentina", "Martina", "Camila", "Florencia", "Agustina", "Sofía", "Lucía", "Julieta", "Catalina", "Milagros", "Guadalupe", "Rocío", "Brisa", "Celeste", "Delfina", "Emilia", "Francesca", "Jazmín", "Lara", "Morena"],
        "surnames": ["Fernández", "Rodríguez", "González", "López", "Martínez", "García", "Romero", "Díaz", "Álvarez", "Ruiz", "Torres", "Gutiérrez", "Pereyra", "Sánchez", "Acosta", "Medina", "Benítez", "Suárez", "Castro", "Herrera"],
    },
    {
        "nationality": "Iranian",
        "region": "middle_east",
        "weight": 1.5,
        "first_m": ["Dariush", "Reza", "Ali", "Amir", "Hossein", "Mohammad", "Behzad", "Cyrus", "Farhad", "Kourosh", "Mehdi", "Nader", "Omid", "Parviz", "Ramin", "Saeed", "Siavash", "Kamran", "Babak", "Arash", "Behnam", "Dara", "Ehsan", "Farzad", "Hamid", "Javad", "Kaveh", "Majid", "Navid", "Shahram"],
        "first_f": ["Shirin", "Azadeh", "Nasrin", "Parisa", "Maryam", "Leila", "Fatemeh", "Zahra", "Sarvenaz", "Roxana", "Anahita", "Bahar", "Darya", "Elnaz", "Faranak", "Golnar", "Hedieh", "Kimia", "Mahsa", "Niloufar", "Pantea", "Roshanak", "Setareh", "Taraneh", "Vida", "Yasaman", "Zhila", "Azar", "Bita", "Dorsa"],
        "surnames": ["Ahmadi", "Hosseini", "Mohammadi", "Rezaei", "Hashemi", "Mousavi", "Karimi", "Ebrahimi", "Moradi", "Jafari", "Rahimi", "Ghorbani", "Kazemi", "Bakhtiari", "Darvishi", "Eslami", "Farahani", "Golestan", "Khorasani", "Shirazi"],
    },
    {
        "nationality": "Turkish",
        "region": "middle_east",
        "weight": 2.0,
        "first_m": ["Mehmet", "Mustafa", "Ahmet", "Ali", "Hüseyin", "İbrahim", "Hasan", "Emre", "Burak", "Kaan", "Barış", "Cem", "Deniz", "Erdem", "Faruk", "Gökhan", "Halil", "İsmail", "Kerem", "Levent", "Murat", "Necati", "Oğuz", "Polat", "Rıza", "Serkan", "Tarık", "Uğur", "Volkan", "Yılmaz"],
        "first_f": ["Ayşe", "Fatma", "Emine", "Hatice", "Zeynep", "Elif", "Merve", "Defne", "Selin", "Ebru", "Başak", "Canan", "Didem", "Esra", "Filiz", "Gülşen", "Hülya", "İpek", "Jale", "Kezban", "Lale", "Melek", "Naz", "Özge", "Pınar", "Rana", "Sevgi", "Tuba", "Ülkü", "Yasemin"],
        "surnames": ["Yılmaz", "Kaya", "Demir", "Çelik", "Şahin", "Yıldız", "Yıldırım", "Öztürk", "Aydın", "Özdemir", "Arslan", "Doğan", "Kılıç", "Aslan", "Çetin", "Koç", "Kurt", "Özkan", "Şimşek", "Polat", "Aktaş", "Balcı", "Coşkun", "Durmaz", "Erdoğan", "Güler", "Kaplan", "Korkmaz", "Tuncer", "Uçar"],
    },
    {
        "nationality": "Egyptian",
        "region": "middle_east",
        "weight": 1.5,
        "first_m": ["Ahmed", "Mohamed", "Mahmoud", "Omar", "Youssef", "Kareem", "Tarek", "Amr", "Sherif", "Hesham", "Bassem", "Ehab", "Gamal", "Hatem", "Ihab", "Khaled", "Magdy", "Nabil", "Ramy", "Samir"],
        "first_f": ["Fatma", "Nour", "Yasmin", "Hala", "Dina", "Rania", "Mona", "Salma", "Aya", "Layla", "Amira", "Basma", "Dalal", "Farida", "Ghada", "Hanaa", "Ingy", "Jihan", "Lobna", "Manal"],
        "surnames": ["El-Sayed", "Hassan", "Ibrahim", "Abdel-Fattah", "Abdel-Rahman", "Mostafa", "Abbas", "Farouk", "Mansour", "Naguib", "Badawi", "Darwish", "El-Shamy", "Gaber", "Hamdy", "Ismail", "Kamal", "Lutfi", "Morsi", "Osman"],
    },
    {
        "nationality": "Nigerian",
        "region": "africa",
        "weight": 2.0,
        "first_m": ["Chiwetel", "Adewale", "Olumide", "Chukwuemeka", "Babatunde", "Femi", "Nnamdi", "Obinna", "Tunde", "Uche", "Adebayo", "Bolaji", "Chidi", "Dayo", "Emeka", "Folarin", "Gbenga", "Hakeem", "Ikenna", "Jide", "Kunle", "Ladi", "Musa", "Nduka", "Olusegun", "Segun", "Taiwo", "Uzoma", "Wale", "Yinka"],
        "first_f": ["Ngozi", "Chioma", "Adaeze", "Funke", "Oluchi", "Nneka", "Amaka", "Bimpe", "Chiamaka", "Damilola", "Enitan", "Folake", "Genevieve", "Halima", "Ifeoma", "Jumoke", "Kemi", "Lola", "Mosunmola", "Nkechi", "Obiageli", "Sade", "Temitope", "Uchenna", "Wunmi", "Yetunde", "Zainab", "Abiola", "Bukola", "Chinyere"],
        "surnames": ["Adeyemi", "Okafor", "Okonkwo", "Bakare", "Eze", "Nwosu", "Abubakar", "Ogunyemi", "Fashola", "Adekunle", "Balogun", "Chukwu", "Danjuma", "Ekwueme", "Fasanmi", "Gbadamosi", "Igwe", "Jakande", "Kalu", "Lawal", "Mbadinuju", "Nwankwo", "Ogundipe", "Sowande", "Uzodinma", "Ibrahim", "Aliyu", "Yusuf", "Garba", "Sule"],
    },
    {
        "nationality": "South African",
        "region": "africa",
        "weight": 1.5,
        "first_m": ["Thabo", "Sipho", "Bongani", "Mandla", "Sibusiso", "Vusi", "Nkosinathi", "Andile", "Tshepo", "Kagiso", "Dumisani", "Fezile", "Gift", "Henk", "Jabu", "Kabelo", "Lebo", "Mpho", "Nhlanhla", "Pieter"],
        "first_f": ["Nomzamo", "Thandi", "Zinhle", "Bongi", "Naledi", "Lerato", "Ayanda", "Nonhlanhla", "Lindiwe", "Minenhle", "Busisiwe", "Duduzile", "Fikile", "Gcina", "Hlengiwe", "Itumeleng", "Jabulile", "Khanyisile", "Lulama", "Mbali"],
        "surnames": ["Ndlovu", "Nkosi", "Dlamini", "Zulu", "Mthembu", "Khumalo", "Naidoo", "Govender", "Pillay", "Maharaj", "Botha", "Van der Merwe", "Pretorius", "Du Plessis", "Joubert", "Venter", "Swanepoel", "Cilliers", "Erasmus", "Fourie"],
    },
    {
        "nationality": "Filipino",
        "region": "southeast_asia",
        "weight": 1.5,
        "first_m": ["Jose", "Juan", "Miguel", "Rafael", "Andres", "Fernando", "Gabriel", "Alejandro", "Benigno", "Carlos", "Dante", "Emilio", "Fidel", "Gregorio", "Isagani", "Julio", "Leandro", "Marcelo", "Nestor", "Ramon"],
        "first_f": ["Maria", "Ana", "Rosa", "Luz", "Fe", "Esperanza", "Caridad", "Remedios", "Corazon", "Lourdes", "Estrella", "Florencia", "Gabriela", "Imelda", "Josefina", "Katherine", "Leonora", "Milagros", "Natividad", "Pilar"],
        "surnames": ["Santos", "Reyes", "Cruz", "Bautista", "Del Rosario", "Gonzales", "Ramos", "Aquino", "Mendoza", "Garcia", "Villanueva", "De Leon", "Pascual", "Rivera", "Navarro", "Torres", "Flores", "Soriano", "Castillo", "Tan"],
    },
    {
        "nationality": "Vietnamese",
        "region": "southeast_asia",
        "weight": 1.5,
        "first_m": ["Minh", "Tuan", "Duc", "Thanh", "Hung", "Quang", "Hieu", "Khoa", "Long", "Phuc", "An", "Bao", "Cuong", "Dung", "Giang", "Hai", "Khanh", "Lam", "Nam", "Son"],
        "first_f": ["Linh", "Huong", "Thao", "Mai", "Ngoc", "Phuong", "Anh", "Ly", "Trang", "Van", "Bich", "Chi", "Dao", "Ha", "Kim", "Lan", "My", "Nhu", "Quynh", "Tam"],
        "surnames": ["Nguyen", "Tran", "Le", "Pham", "Hoang", "Huynh", "Phan", "Vu", "Vo", "Dang", "Bui", "Do", "Ho", "Ngo", "Duong", "Ly", "Truong", "Dinh", "Luu", "Mai"],
    },
    {
        "nationality": "Thai",
        "region": "southeast_asia",
        "weight": 1.0,
        "first_m": ["Somchai", "Thaksin", "Prayut", "Anand", "Bhumibol", "Chuan", "Kittisak", "Nattapong", "Pichit", "Sakchai", "Tanawat", "Ukrit", "Wichai", "Apichart", "Boonchai", "Chaiyuth", "Danai", "Ekachai", "Jaturon", "Methee"],
        "first_f": ["Somying", "Pimchanok", "Araya", "Narisara", "Lalita", "Malinee", "Kamonwan", "Busaba", "Chutima", "Duangjai", "Fah", "Hathai", "Issaree", "Jiraporn", "Kannika", "Lawan", "Manee", "Nit", "Orn", "Panida"],
        "surnames": ["Wongsawat", "Chunhawan", "Pramoj", "Shinawatra", "Vejjajiva", "Abhisit", "Boonchu", "Charoen", "Kittikachorn", "Limthongkul", "Silpa-archa", "Suchinda", "Thienthong", "Chearavanont", "Damrongchaitham", "Jiaravanon", "Maleenont", "Osathanugrah", "Sophonpanich", "Viriyaprapaikit"],
    },
    {
        "nationality": "Russian",
        "region": "europe",
        "weight": 2.5,
        "first_m": ["Dmitri", "Alexei", "Vladimir", "Sergei", "Nikolai", "Mikhail", "Andrei", "Yuri", "Ivan", "Boris", "Fyodor", "Grigori", "Igor", "Kirill", "Leonid", "Maxim", "Oleg", "Pavel", "Roman", "Stanislav", "Artyom", "Bogdan", "Daniil", "Evgeni", "Georgi", "Ilya", "Konstantin", "Matvei", "Pyotr", "Timofei"],
        "first_f": ["Anastasia", "Natalia", "Tatiana", "Ekaterina", "Olga", "Maria", "Irina", "Elena", "Anna", "Svetlana", "Yulia", "Daria", "Ksenia", "Polina", "Valeria", "Sofia", "Alina", "Evgenia", "Galina", "Lyudmila", "Alexandra", "Vera", "Nadezhda", "Larisa", "Marina", "Nina", "Raisa", "Tamara", "Valentina", "Zoya"],
        "surnames": ["Ivanov", "Petrov", "Smirnov", "Kuznetsov", "Popov", "Sokolov", "Lebedev", "Kozlov", "Novikov", "Morozov", "Volkov", "Solovyov", "Vasiliev", "Zaitsev", "Pavlov", "Semyonov", "Golubev", "Vinogradov", "Bogdanov", "Voronov", "Alekseev", "Belov", "Egorov", "Fedorov", "Gromov", "Kovalev", "Orlov", "Ryabov", "Sidorov", "Titov"],
    },
    {
        "nationality": "Polish",
        "region": "europe",
        "weight": 1.5,
        "first_m": ["Andrzej", "Bartosz", "Czesław", "Damian", "Filip", "Grzegorz", "Jakub", "Krzysztof", "Łukasz", "Marcin", "Michał", "Paweł", "Piotr", "Rafał", "Szymon", "Tomasz", "Wojciech", "Zbigniew", "Marek", "Janusz"],
        "first_f": ["Agnieszka", "Beata", "Dorota", "Ewa", "Grażyna", "Hanna", "Iwona", "Joanna", "Katarzyna", "Magdalena", "Małgorzata", "Monika", "Patrycja", "Renata", "Sylwia", "Urszula", "Weronika", "Zofia", "Anna", "Barbara"],
        "surnames": ["Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kowalczyk", "Kamiński", "Lewandowski", "Zieliński", "Szymański", "Woźniak", "Dąbrowski", "Kozłowski", "Jankowski", "Mazur", "Kwiatkowski", "Krawczyk", "Piotrowski", "Grabowski", "Pawlak", "Michalski"],
    },
    {
        "nationality": "Ukrainian",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["Oleksandr", "Dmytro", "Andriy", "Bohdan", "Volodymyr", "Taras", "Yaroslav", "Mykola", "Serhiy", "Petro", "Ihor", "Vasyl", "Kyrylo", "Orest", "Ruslan", "Stepan", "Maksym", "Danylo", "Ostap", "Zenon"],
        "first_f": ["Oksana", "Halyna", "Iryna", "Lesya", "Natalia", "Olena", "Svitlana", "Tetiana", "Yaryna", "Zoryana", "Bohdana", "Daryna", "Ivanna", "Kalyna", "Larysa", "Maryna", "Nadiya", "Roksolana", "Solomiia", "Ulyana"],
        "surnames": ["Shevchenko", "Kovalenko", "Bondarenko", "Tkachenko", "Kravchenko", "Oliynik", "Marchenko", "Savchenko", "Rudenko", "Klymenko", "Boyko", "Gavrylyuk", "Hrytsenko", "Ivanenko", "Kyrychenko", "Lysenko", "Melnyk", "Ponomarenko", "Sydorenko", "Tymoshchuk"],
    },
    {
        "nationality": "Swedish",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["Erik", "Lars", "Anders", "Karl", "Johan", "Nils", "Per", "Olof", "Sven", "Magnus", "Gustaf", "Björn", "Axel", "Viktor", "Oscar", "Hugo", "Albin", "Sigurd", "Torsten", "Linus"],
        "first_f": ["Maria", "Anna", "Ingrid", "Astrid", "Elsa", "Greta", "Linnea", "Freja", "Saga", "Maja", "Ebba", "Stella", "Klara", "Lovisa", "Agnes", "Hedvig", "Sigrid", "Tyra", "Alva", "Hildur"],
        "surnames": ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson", "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson", "Lindberg", "Lindqvist", "Lindgren", "Bergström", "Nyström"],
    },
    {
        "nationality": "Norwegian",
        "region": "europe",
        "weight": 0.8,
        "first_m": ["Bjørn", "Erik", "Harald", "Leif", "Ole", "Torbjørn", "Sigurd", "Ragnar", "Einar", "Halvard", "Knut", "Arne", "Gunnar", "Ivar", "Magnus", "Njål", "Stein", "Trygve", "Vidar", "Øystein"],
        "first_f": ["Ingrid", "Astrid", "Solveig", "Freya", "Sigrid", "Ragnhild", "Gunnhild", "Helga", "Gudrun", "Liv", "Anja", "Berit", "Dagny", "Elin", "Hege", "Kari", "Marit", "Randi", "Silje", "Tone"],
        "surnames": ["Hansen", "Johansen", "Olsen", "Larsen", "Andersen", "Pedersen", "Nilsen", "Kristiansen", "Jensen", "Karlsen", "Eriksen", "Johnsen", "Pettersen", "Hagen", "Haugen", "Bakken", "Lund", "Strand", "Solberg", "Berg"],
    },
    {
        "nationality": "Greek",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["Nikos", "Giorgos", "Dimitris", "Kostas", "Yannis", "Christos", "Panagiotis", "Vassilis", "Theodoros", "Michalis", "Alexandros", "Apostolos", "Evangelos", "Spyros", "Stavros", "Thanasis", "Sotiris", "Ilias", "Angelos", "Pavlos"],
        "first_f": ["Maria", "Eleni", "Katerina", "Georgia", "Ioanna", "Sofia", "Dimitra", "Anastasia", "Vasiliki", "Fotini", "Athena", "Calliope", "Despina", "Efthymia", "Foteini", "Helena", "Irini", "Konstantina", "Penelope", "Thalia"],
        "surnames": ["Papadopoulos", "Vlahos", "Angelopoulos", "Nikolaidis", "Georgiou", "Dimitriou", "Papageorgiou", "Ioannou", "Konstantinou", "Alexiou", "Christodoulou", "Economou", "Giannopoulos", "Karamanlis", "Makris", "Pappas", "Stavropoulos", "Theodorakis", "Vasileiou", "Xenakis"],
    },
    {
        "nationality": "Dutch",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["Jan", "Pieter", "Willem", "Hendrik", "Cornelis", "Johannes", "Gerrit", "Dirk", "Jacobus", "Adriaan", "Bas", "Daan", "Joost", "Maarten", "Niels", "Remco", "Sander", "Thijs", "Wouter", "Bram"],
        "first_f": ["Maria", "Anna", "Johanna", "Cornelia", "Wilhelmina", "Hendrika", "Elisabeth", "Geertruida", "Adriana", "Margaretha", "Daphne", "Femke", "Ilse", "Lotte", "Marieke", "Nienke", "Roos", "Sanne", "Tessa", "Wieke"],
        "surnames": ["De Vries", "Van den Berg", "Van Dijk", "Bakker", "Jansen", "Visser", "Smit", "Meijer", "De Boer", "Mulder", "De Groot", "Bos", "Vos", "Peters", "Hendriks", "Van Leeuwen", "Dekker", "Brouwer", "De Wit", "Dijkstra"],
    },
    {
        "nationality": "Portuguese",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["João", "Pedro", "Miguel", "António", "Francisco", "Manuel", "Rui", "Nuno", "Tiago", "Diogo", "André", "Bruno", "Hugo", "Rafael", "Gonçalo", "Filipe", "Ricardo", "Bernardo", "Tomás", "Vasco"],
        "first_f": ["Maria", "Ana", "Joana", "Inês", "Margarida", "Beatriz", "Leonor", "Matilde", "Carolina", "Francisca", "Sofia", "Catarina", "Madalena", "Teresa", "Isabel", "Helena", "Rita", "Constança", "Benedita", "Mariana"],
        "surnames": ["Silva", "Santos", "Ferreira", "Pereira", "Oliveira", "Costa", "Rodrigues", "Martins", "Sousa", "Fernandes", "Gomes", "Lopes", "Marques", "Alves", "Almeida", "Ribeiro", "Pinto", "Carvalho", "Teixeira", "Correia"],
    },
    {
        "nationality": "Irish",
        "region": "europe",
        "weight": 1.0,
        "first_m": ["Sean", "Patrick", "Conor", "Liam", "Ciaran", "Declan", "Oisin", "Cillian", "Fionn", "Padraig", "Brendan", "Cathal", "Darragh", "Eamon", "Fergal", "Gareth", "Killian", "Lorcan", "Niall", "Ronan"],
        "first_f": ["Siobhan", "Saoirse", "Aoife", "Niamh", "Ciara", "Roisin", "Aisling", "Caoimhe", "Maeve", "Orla", "Brigid", "Clodagh", "Eimear", "Fiona", "Grainne", "Iona", "Keelin", "Laoise", "Muireann", "Sinead"],
        "surnames": ["Murphy", "Kelly", "O'Sullivan", "Walsh", "Smith", "O'Brien", "Byrne", "Ryan", "O'Connor", "O'Neill", "McCarthy", "O'Reilly", "Doherty", "Kennedy", "Lynch", "Murray", "Quinn", "Moore", "McLaughlin", "Gallagher"],
    },
    {
        "nationality": "Hungarian",
        "region": "europe",
        "weight": 0.8,
        "first_m": ["László", "István", "József", "János", "Gábor", "Zoltán", "Tamás", "Attila", "Béla", "Csaba", "Gyula", "Imre", "Lajos", "Miklós", "Pál", "Sándor", "Tibor", "Viktor", "Ákos", "Bence"],
        "first_f": ["Erzsébet", "Katalin", "Mária", "Éva", "Ilona", "Zsuzsa", "Ágnes", "Judit", "Krisztina", "Annamária", "Boglárka", "Csilla", "Dorottya", "Emese", "Fruzsina", "Henrietta", "Kinga", "Lilla", "Nóra", "Virág"],
        "surnames": ["Kovács", "Nagy", "Szabó", "Tóth", "Horváth", "Varga", "Kiss", "Molnár", "Németh", "Farkas", "Balogh", "Papp", "Takács", "Juhász", "Lakatos", "Mészáros", "Oláh", "Rácz", "Fehér", "Szilágyi"],
    },
    {
        "nationality": "Czech",
        "region": "europe",
        "weight": 0.8,
        "first_m": ["Jan", "Petr", "Tomáš", "Martin", "Pavel", "Jakub", "Jiří", "Michal", "Lukáš", "Ondřej", "Adam", "David", "Filip", "Karel", "Marek", "Radek", "Stanislav", "Václav", "Vladimír", "Zdeněk"],
        "first_f": ["Jana", "Marie", "Eva", "Anna", "Hana", "Lenka", "Kateřina", "Petra", "Lucie", "Markéta", "Adéla", "Barbora", "Daniela", "Eliška", "Ivana", "Klára", "Martina", "Renáta", "Tereza", "Veronika"],
        "surnames": ["Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka", "Kučera", "Veselý", "Horák", "Němec", "Pokorný", "Marek", "Pospíšil", "Hájek", "Jelínek", "Král", "Růžička", "Beneš", "Fiala", "Sedláček"],
    },
    {
        "nationality": "Romanian",
        "region": "europe",
        "weight": 0.8,
        "first_m": ["Ion", "Gheorghe", "Vasile", "Alexandru", "Mihai", "Andrei", "Cristian", "Bogdan", "Dragoș", "Florin", "Lucian", "Marius", "Nicolae", "Ovidiu", "Radu", "Ștefan", "Traian", "Valentin", "Adrian", "Dan"],
        "first_f": ["Maria", "Elena", "Ana", "Ioana", "Andreea", "Cristina", "Mihaela", "Raluca", "Simona", "Diana", "Alina", "Bianca", "Carmen", "Daniela", "Florina", "Gabriela", "Laura", "Mădălina", "Oana", "Roxana"],
        "surnames": ["Popescu", "Ionescu", "Popa", "Dumitru", "Stan", "Stoica", "Gheorghe", "Rusu", "Moldovan", "Marin", "Constantin", "Toma", "Ciobanu", "Matei", "Nistor", "Barbu", "Cristea", "Florea", "Mihai", "Tudor"],
    },
]
