#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASE_DIR"

export RUN_PROFILE=candidate100k_2000_2050
export LLM_PROVIDER=gemini
export MIRAGE_DEFAULT_GEMINI_MODEL="${MIRAGE_DEFAULT_GEMINI_MODEL:-gemini-3.1-flash-lite}"
export MIRAGE_DEFAULT_GEMINI_PRO_MODEL="${MIRAGE_DEFAULT_GEMINI_PRO_MODEL:-gemini-3.1-flash-lite}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"

export DATA_SYS_LLM_USAGE_LOG="${DATA_SYS_LLM_USAGE_LOG:-$BASE_DIR/reports/gemini_100k_2000_2050_usage.jsonl}"
export DATA_SYS_LLM_USAGE_LOG_LATEST="${DATA_SYS_LLM_USAGE_LOG_LATEST:-$BASE_DIR/reports/gemini_100k_2000_2050_usage_latest.jsonl}"
export DATA_SYS_LLM_MAX_ATTEMPTS="${DATA_SYS_LLM_MAX_ATTEMPTS:-5}"
export DATA_SYS_LLM_TIMEOUT_SEC="${DATA_SYS_LLM_TIMEOUT_SEC:-180}"
export DATA_SYS_LLM_BASE_DELAY_SEC="${DATA_SYS_LLM_BASE_DELAY_SEC:-2}"
export DATA_SYS_LLM_MAX_DELAY_SEC="${DATA_SYS_LLM_MAX_DELAY_SEC:-60}"
export DATA_SYS_PERSON_ENRICH_BATCH_SIZE="${DATA_SYS_PERSON_ENRICH_BATCH_SIZE:-100}"
export DATA_SYS_LATENT_BATCH_SIZE="${DATA_SYS_LATENT_BATCH_SIZE:-100}"

export DATA_SYS_SKIP_DIAGNOSTIC_COLD_EDGES="${DATA_SYS_SKIP_DIAGNOSTIC_COLD_EDGES:-1}"
export DATA_SYS_FAST_TITLE_TAGLINES="${DATA_SYS_FAST_TITLE_TAGLINES:-1}"

exec ./run_lab_local_llm.sh profile-full100
